Code cleanup
nats-io/nats.c pull request #401
Opened 2021-01-27 13:09 UTC by vabalas

**This is a draft PR.** Following the helpful feedback from @kozlovic (See #400) I want to wrap the culprit `freeaddrinfo()` with a null check. 

Sorry for disturbing you because of a minor nuisance, but could you please indicate in which header should I put it (since `util.h` is not included everywhere)?

I appreciate your help!

2021-01-27 16:41 UTC, kozlovic requested changes
Suggested some changes to fix compilation errors.

2021-01-27 16:41 UTC, kozlovic commented on src/util.c
> +void nats_FreeAddrInfo(struct addrinfo *res)
To follow the code style and fix the issue reported on compile, I would write like this:
```
void
nats_FreeAddrInfo(struct addrinfo *res)
{
    // Calling freeaddrinfo(NULL) is undefined behaviour.
    if (res == NULL)
        return;

    freeaddrinfo(res);
}
```

2021-01-27 16:41 UTC, kozlovic commented on src/comsock.c
> +            nats_FreeAddrInfo(servInfos[i]);
You need to add:
```
#include "util.h"
```
at top of this file.

2021-01-28 06:39 UTC, vabalas commented
I appreciate your help very much! I added the amendments you requested.

2021-01-28 15:49 UTC, kozlovic approved these changes
LGTM

2021-01-28 15:50 UTC, merged