add natsOptions_SetUserCredentialsFromMemory
nats-io/nats.c pull request #621
Opened 2023-01-01 18:37 UTC by MichaelVoelkel

I would say, this is very useful (I need it myself) because I am actually getting the JWT as env var in some docker container. I could write it to a file and then read that but it feels like unnecessary file I/O so I would rather directly read from memory.

I tested it personally and it works.

I can add UTs if you generally would accept this change (otherwise I'd rather save the time :)).

2023-01-02 22:22 UTC, kozlovic requested changes
Since this would be a new API, I would like you to rebase your PR from the `dev` branch and re-post. When you submit a PR you can select the base branch to submit against.

But also, I would prefer that we extend the `userCreds` struct and add a new field that would be a copy of the `memory` passed to the new API. But otherwise it would be very similar to natsOptions_SetUserCredentialsFromFiles(). I would simply rename `natsConn_userFromFile` to `natsConn_userCreds` or something like that and check for the new field in _sign() and the renamed `natsConn_userFromFile`. In other words, I think we can get away with the single new option API. Could you try?

2023-01-02 22:22 UTC, kozlovic commented on src/nats.h
> + * from a file. Also it assumes that `memory` contains both the JWT and NKey seed. Note that the format of memory is:
Looks like the sentence is not finished.

2023-01-03 17:15 UTC, MichaelVoelkel commented
> Since this would be a new API, I would like you to rebase your PR from the `dev` branch and re-post. When you submit a PR you can select the base branch to submit against.
> 
> But also, I would prefer that we extend the `userCreds` struct and add a new field that would be a copy of the `memory` passed to the new API. But otherwise it would be very similar to natsOptions_SetUserCredentialsFromFiles(). I would simply rename `natsConn_userFromFile` to `natsConn_userCreds` or something like that and check for the new field in _sign() and the renamed `natsConn_userFromFile`. In other words, I think we can get away with the single new option API. Could you try?

Understood and why not!

Just one note: It would not only be `natsConn_userFromFile` (or the renamed version) but also `natsConn_signatureHandler` getting a change because the previous signature handler also needs the info and extracted it from file.

But I can also check that.

2023-01-04 17:13 UTC, MichaelVoelkel commented
Okay, so this version also has some test. I just assumed it's fine to put it next to the tests for UserCredsFromFiles...

Whenever I push here, some tests fail. Are some flaky or is this expected?

Also, would you like to see an addition to `examples.h`?

2023-01-04 20:03 UTC, kozlovic requested changes
Thanks Michael. This is a very good PR. There is just a small bug checking for memory allocation failure, and you need to include the new test in the test suite list by following the instructions that I have directed you too (I did it locally and your new test passes and does not have memory leak, but as of now it is not run in the PR itself).
Also, I would like you to squash to a single commit when I will approve and before I merge. Thanks again!

2023-01-05 15:19 UTC, MichaelVoelkel commented
Forgot to push yesterday evening. Anyways, some things to mention with current behaviour:

- if `natsOptions_SetUserCredentialsFromMemory` is called with content `NULL`, then the content will be cleared
- if not, then the content will first be checked (i.e. does it have two items)... as this is content that should be nulled, there exists `natsCrypto_Clear` which I used but it means another header include is necessary
- for `natsOptions_SetUserCredentialsFromFiles`, the check of files is not done until the connect is actually made... that is why originally I did it the same way. If the function needs to check the two lines, it's a bit more effort and also different behaviour from `natsOptions_SetUserCredentialsFromFiles` - fine for me, just wanted to point it out

The tests mirror the behaviour, so it can be observed.

2023-01-05 16:41 UTC, kozlovic requested changes
Sorry about that. You are right, we want to be consistent, so let's have the test attempt the connect instead.

2023-01-05 16:42 UTC, kozlovic requested changes

2023-01-05 16:43 UTC, MichaelVoelkel commented on src/opts.c
> +        for (int item = 0; item < 2; ++item)
Sure, will do it!

2023-01-05 17:05 UTC, MichaelVoelkel commented on src/opts.c
> +        for (int item = 0; item < 2; ++item)
Done. Apart from one test that crashes, tests are also fine (although I don't get why it crashes?) Locally the test succeeds

2023-01-05 21:11 UTC, kozlovic commented on src/opts.c
> +        for (int item = 0; item < 2; ++item)
Likely a flapper. All good, going to merge the PR. Thanks again!

2023-01-05 21:11 UTC, kozlovic approved these changes
LGTM. Thank you for your contribution!

2023-01-05 21:11 UTC, merged