added `natsConn_(get|set)(Error|Closed)Callback`
nats-io/nats.c pull request #647
Opened 2023-04-06 20:42 UTC by levb

To use in the microservices implementation, to wrap connection handlers on an active connection.

(still need to add a test for `setClosedCallback`)

2023-04-06 21:30 UTC, kozlovic requested changes
Tests are failing (does not seem to be flapping since the same tests fail in various matrix runs). It could be because of the extra `break` that I pointed out, but not sure.

2023-04-06 21:30 UTC, kozlovic commented on test/test.c
> +    {"AsyncSetErrHandler",              test_AsyncSetErrHandler},
This is not enough to add a test to the test suite. Follow instructions [here](https://github.com/nats-io/nats.c#testing).

2023-04-06 21:31 UTC, kozlovic commented on src/nats.c
> +        natsMutex_Lock(nc->mu);
You would also need to reset cbHandler/Closure and errHandler/closure in each loop iteration!

2023-04-06 21:47 UTC, levb commented
Oops, @kozlovic sorry I tagged you too early; I pushed to run the tests, still finishing this up. Thanks for jumping onto it!

2023-04-07 17:39 UTC, kozlovic approved these changes
LGTM. Just a note, since recently, it is assumed that the async error callback will always be set (if not set by the user, we use a default handler that prints to stderr, see `natsConn_defaultErrHandler`). I see that your new setter does not allow NULL, so there is no risk at the moment that you would remove the error handler. If you do in the future, check invocations of `natsAsyncCb_PostErrHandler` that again assume that a callback is always set.

2023-04-26 19:14 UTC, levb commented
#640 has an improved implementation, closing this PR.

2023-04-26 19:14 UTC, closed without merging