Expose MaxPendingBytes on the natsOptions
nats-io/nats.c pull request #700
Opened 2023-11-27 12:02 UTC by LaurensVergote

Similar as https://github.com/nats-io/nats.net/pull/844 from the nats.net library.

Couldn't get the testsuite to work locally so I hope the github pipeline will run them :)

2023-11-28 15:08 UTC, LaurensVergote commented
Not quite sure why the CI timed out on one of the new tests, had no issues locally running it

2023-11-28 16:27 UTC, kozlovic commented on test/test.c
> +    for (int i = 0;
For code consistency. It came from a time where - I believe on Windows, with whatever compiler version we were using - it was not possible to declare variables there. We could relax that, especially in test.c, but I like to keep things consistent. It also help prevent variable shadowing bugs.

2023-11-30 16:40 UTC, kozlovic requested changes
Let's fix the for loop to not have the warning. But more importantly, we need @levb to confirm if we are still using the `dev` branch for new features. If so, this PR will need to change the base branch from `main` to `dev`. As of now though, I don't think that `dev` is up-to-date, so let's wait on @levb to confirm what we need to do here.

2023-11-30 16:40 UTC, kozlovic commented on test/test.c
> +    for (int i = 0;
That produces warnings:
```
[ 98%] Building C object test/CMakeFiles/testsuite.dir/test.c.o
/home/travis/build/nats-io/nats.c/test/test.c: In function ‘test_AsyncErrHandler_MaxPendingBytes’:
/home/travis/build/nats-io/nats.c/test/test.c:14453:5: warning: statement with no effect [-Wunused-value]
14453 |     for (i;
      |     ^~~
```
Instead, do `for (i=0; ...`.

2023-11-30 16:40 UTC, kozlovic commented on test/test.c
> +    for (i;
Same comment than in the other test.

2024-04-05 14:29 UTC, LaurensVergote commented on test/test.c
> +    for (int i = 0;
Done.

2024-04-05 14:29 UTC, LaurensVergote commented on test/test.c
> +    for (i;
Done

2024-04-05 18:12 UTC, kozlovic approved these changes
LGTM. Will let @levb have a look and merge if he is ok with it.

2024-04-05 20:37 UTC, levb approved these changes
LGTM

2024-04-05 20:37 UTC, merged